# Generated by Django 6.1 on 2026-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_is_featured_alter_testimonial_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
