# Generated by Django 6.1 on 2026-08-14 15:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonial_company_alter_testimonial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
