# Generated by Django 6.1 on 2026-08-14 17:07

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('achievements', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Elvis', max_length=50)),
                ('last_name', models.CharField(default='Harmon', max_length=50)),
                ('display_name', models.CharField(blank=True, default='Elvis T. Harmon', max_length=100)),
                ('email', models.EmailField(default='harmonelvis78@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20)),
                ('location', models.CharField(blank=True, default='San Francisco, CA', max_length=100)),
                ('hero_badge', models.CharField(blank=True, default='Software Engineer', max_length=100, null=True)),
                ('hero_title', models.CharField(blank=True, default='Building Intelligent Software', max_length=200, null=True)),
                ('hero_subtitle', models.CharField(blank=True, default='That Solves Real Problems', max_length=200, null=True)),
                ('welcome_text', models.CharField(blank=True, default="Hello, I'm", max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='Senior Software Engineer', max_length=100, null=True)),
                ('headline', models.CharField(blank=True, default='Building Intelligent Software That Solves Real Problems', max_length=200, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True, max_length=500, null=True)),
                ('hero_description', models.TextField(blank=True, default='A passionate software engineer dedicated to building innovative solutions that make a difference. Specializing in full-stack development, artificial intelligence, and creating impactful technology.', max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('footer_bio', models.TextField(blank=True, default='Building intelligent software that solves real problems.', max_length=300, null=True)),
                ('footer_copyright', models.CharField(blank=True, default='All rights reserved.', max_length=200, null=True)),
                ('footer_email', models.EmailField(blank=True, default='harmonelvis78@gmail.com', max_length=254, null=True)),
                ('footer_phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20, null=True)),
                ('footer_location', models.CharField(blank=True, default='San Francisco, CA', max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('about_image', models.ImageField(blank=True, help_text='Square image for the about page (recommended: 400x400px or larger)', null=True, upload_to='profiles/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', '-years_experience'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, to='profiles.skill')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
