# Generated by Django 6.1 on 2026-08-12 23:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_footer_bio_profile_footer_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='Elvis T. Harmon', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_bio',
            field=models.TextField(blank=True, default='Building intelligent software that solves real problems.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_copyright',
            field=models.CharField(blank=True, default='All rights reserved.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_email',
            field=models.EmailField(blank=True, default='harmonelvis78@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_location',
            field=models.CharField(blank=True, default='San Francisco, CA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_phone',
            field=models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, default='Building Intelligent Software That Solves Real Problems', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_badge',
            field=models.CharField(blank=True, default='Software Engineer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_description',
            field=models.TextField(blank=True, default='A passionate software engineer dedicated to building innovative solutions that make a difference. Specializing in full-stack development, artificial intelligence, and creating impactful technology.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='That Solves Real Problems', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_title',
            field=models.CharField(blank=True, default='Building Intelligent Software', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='Senior Software Engineer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='welcome_text',
            field=models.CharField(blank=True, default="Hello, I'm", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
