# Generated by Django 6.1 on 2026-08-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_certification_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_content_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_filename',
            field=models.CharField(blank=True, default='Elvis_Harmon_CV.pdf', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_description',
            field=models.TextField(blank=True, default='A passionate software engineer dedicated to building innovative solutions that make a difference. Specializing in full-stack development, artificial intelligence, and creating impactful technology.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
