# Generated by Django 6.1 on 2026-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_resume_content_type_profile_resume_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
