# Generated by Django 6.1 on 2026-08-13 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_bio_alter_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Square image for the about page (recommended: 400x400px or larger)', null=True, upload_to='profiles/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
