# Generated by Django 6.1 on 2026-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=20000),
        ),
    ]
