# Generated by Django 6.1 on 2026-08-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CONCEPT', 'Concept')], default='COMPLETED', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex color code', max_length=20),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=1000),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
