# Generated by Django 6.1 on 2026-08-12 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('WEB_DEVELOPMENT', 'Web Development'), ('DJANGO_DEVELOPMENT', 'Django Development'), ('AI_ML', 'AI/ML Development'), ('API_DEVELOPMENT', 'API Development'), ('DATABASE_DEVELOPMENT', 'Database Development'), ('SOFTWARE_ENGINEERING', 'Software Engineering'), ('TECHNICAL_CONSULTING', 'Technical Consulting'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('budget', models.CharField(choices=[('UNDER_1000', 'Under $1,000'), ('_1000_5000', '$1,000 - $5,000'), ('_5000_10000', '$5,000 - $10,000'), ('_10000_25000', '$10,000 - $25,000'), ('_25000_50000', '$25,000 - $50,000'), ('_50000_PLUS', '$50,000+'), ('NOT_SPECIFIED', 'Not Specified')], default='NOT_SPECIFIED', max_length=20)),
                ('timeline', models.CharField(choices=[('URGENT', 'Urgent (Within 1 week)'), ('SHORT', 'Short (1-4 weeks)'), ('MEDIUM', 'Medium (1-3 months)'), ('LONG', 'Long (3-6 months)'), ('FLEXIBLE', 'Flexible'), ('NOT_SPECIFIED', 'Not Specified')], default='FLEXIBLE', max_length=20)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('IN_DISCUSSION', 'In Discussion'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contact_con_email_233940_idx'), models.Index(fields=['status'], name='contact_con_status_fa3e24_idx'), models.Index(fields=['created_at'], name='contact_con_created_fddb83_idx')],
            },
        ),
    ]
