# Generated by Django 6.1 on 2026-08-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(choices=[('UNDER_1000', 'Under $1,000'), ('_1000_5000', '$1,000 - $5,000'), ('_5000_10000', '$5,000 - $10,000'), ('_10000_25000', '$10,000 - $25,000'), ('_25000_50000', '$25,000 - $50,000'), ('_50000_PLUS', '$50,000+'), ('NOT_SPECIFIED', 'Not Specified')], default='NOT_SPECIFIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(choices=[('WEB_DEVELOPMENT', 'Web Development'), ('DJANGO_DEVELOPMENT', 'Django Development'), ('AI_ML', 'AI/ML Development'), ('API_DEVELOPMENT', 'API Development'), ('DATABASE_DEVELOPMENT', 'Database Development'), ('SOFTWARE_ENGINEERING', 'Software Engineering'), ('TECHNICAL_CONSULTING', 'Technical Consulting'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('IN_DISCUSSION', 'In Discussion'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='timeline',
            field=models.CharField(choices=[('URGENT', 'Urgent (Within 1 week)'), ('SHORT', 'Short (1-4 weeks)'), ('MEDIUM', 'Medium (1-3 months)'), ('LONG', 'Long (3-6 months)'), ('FLEXIBLE', 'Flexible'), ('NOT_SPECIFIED', 'Not Specified')], default='FLEXIBLE', max_length=30),
        ),
    ]
