# Generated by Django 6.1 on 2026-08-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Elvis T. Harmon', max_length=100)),
                ('site_tagline', models.CharField(default='Building Intelligent Software That Solves Real Problems', max_length=200)),
                ('site_description', models.TextField(default='Professional portfolio of Elvis T. Harmon, a software engineer specializing in Django, Python, AI/ML, and full-stack development.')),
                ('admin_email', models.EmailField(default='harmonelvis78@gmail.com', max_length=254)),
                ('default_from_email', models.EmailField(default='noreply@elvisportfolio.com', max_length=254)),
                ('email_subject_prefix', models.CharField(default='[Contact Form] ', max_length=50)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#6C63FF', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#3F3D9E', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#FF6B6B', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Inter', help_text='Google Font name', max_length=100)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('meta_title', models.CharField(default='Elvis T. Harmon - Software Engineer', max_length=100)),
                ('meta_description', models.CharField(default='Building intelligent software that solves real problems. Software Engineer specializing in Django, Python, AI/ML, and full-stack development.', max_length=200)),
                ('meta_keywords', models.CharField(blank=True, default='Software Engineer, Django, Python, AI/ML, Full-Stack Developer, Web Development', max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_copyright', models.CharField(default='© 2024 Elvis T. Harmon. All rights reserved.', max_length=200)),
                ('footer_about', models.TextField(default='Building intelligent software that solves real problems.')),
                ('footer_email', models.EmailField(default='harmonelvis78@gmail.com', max_length=254)),
                ('footer_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('footer_location', models.CharField(default='San Francisco, CA', max_length=100)),
                ('footer_quick_links', models.TextField(blank=True, help_text='Comma separated links (e.g., Home, About, Projects, Blog)')),
                ('footer_services', models.TextField(blank=True, help_text='Comma separated services (e.g., Web Development, Django, AI/ML)')),
                ('site_url', models.URLField(blank=True, help_text='Your live site URL', null=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='We are currently undergoing maintenance. Please check back soon.', null=True)),
                ('analytics_code', models.TextField(blank=True, help_text='Custom analytics code (e.g., Google Analytics, Facebook Pixel)', null=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS to override styles', null=True)),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript to add to the site', null=True)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
