# Generated by Django 6.1 on 2026-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_published_at_blogpost_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
