# Generated by Django 6.1 on 2026-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('project_views', models.PositiveIntegerField(default=0)),
                ('blog_views', models.PositiveIntegerField(default=0)),
                ('cv_downloads', models.PositiveIntegerField(default=0)),
                ('contact_submissions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Summary',
                'verbose_name_plural': 'Analytics Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('project_view', 'Project View'), ('blog_view', 'Blog View'), ('cv_download', 'CV Download'), ('contact_submission', 'Contact Submission'), ('search', 'Search')], max_length=100)),
                ('url', models.CharField(max_length=2000)),
                ('referrer', models.URLField(blank=True, max_length=2000, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='analytics_a_event_t_a460ec_idx'), models.Index(fields=['created_at'], name='analytics_a_created_546677_idx'), models.Index(fields=['url'], name='analytics_a_url_c1d225_idx')],
            },
        ),
    ]
