# Generated by Django 6.1 on 2026-08-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('project_views', models.PositiveIntegerField(default=0)),
                ('blog_views', models.PositiveIntegerField(default=0)),
                ('cv_downloads', models.PositiveIntegerField(default=0)),
                ('contact_submissions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Summary',
                'verbose_name_plural': 'Analytics Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('project_view', 'Project View'), ('blog_view', 'Blog View'), ('cv_download', 'CV Download'), ('contact_submission', 'Contact Submission'), ('search', 'Search')], max_length=30),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='analytics_a_event_t_a460ec_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at'], name='analytics_a_created_546677_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['url'], name='analytics_a_url_c1d225_idx'),
        ),
    ]
