# Generated by Django 6.1 on 2026-08-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticssummary_analyticsevent_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsevent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='country',
        ),
    ]
