# Generated by Django 6.1 on 2026-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_analyticsevent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('project_view', 'Project View'), ('blog_view', 'Blog View'), ('cv_download', 'CV Download'), ('contact_submission', 'Contact Submission'), ('search', 'Search')], max_length=100),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='referrer',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
